name: close-opsgenie-alert
description: Close an OpsGenie Alert
inputs:
  api_key:
    description: OpsGenie API key
    required: true
  alias:
    description: Alias of the alert to close
    required: true
  user:
    description: OpsGenie Actor
    required: false
    default: github-action
  note:
    description: Close alert note
    required: false
runs:
  using: 'node16'
  main: 'index.js'