name: Compile index.js

on:
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: yarn install
      - run: yarn global add @vercel/ncc

      - name: Compile all into index.js
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: ncc build index.js --license licenses.txt

      - name: Commit new index.js
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"
          git commit -am "Updated compilation of index.js"
          git push
